FROM node:16

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

RUN npm install

COPY . .

# Build the TypeScript code
RUN npm run build

EXPOSE 8080

# Define the command to run your app
CMD ["node", "dist/server.js"]